[build]
  command = "cd client && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd client && npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
