[web]
command = "gunicorn app.main:app -k uvicorn.workers.UvicornWorker -w 4 --bind 0.0.0.0:$PORT"
env = "python"
buildCommand = "pip install --upgrade pip && pip install -e ."

[web.env]
# MongoDB Configuration
MONGODB_URI = ""

# Frontend Configuration
FRONTEND_URL = ""

# Server Configuration
PORT = "8000"

# Security Settings
SECRET_KEY = ""

# Rate Limiting
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# CORS Settings
ALLOWED_ORIGINS = ""

[web.ports]
8000 = "8000"

[web.healthCheck]
path = "/health"

[database]
name = "resume_extractor"
type = "mongodb"

[database.env]
MONGODB_URI = ""
