[web]
command = "gunicorn app.main:app -k uvicorn.workers.UvicornWorker -w 4 --bind 0.0.0.0:$PORT"
env = "python"
buildCommand = "pip install -r requirements.txt"

[web.env]
# MongoDB URI will be set via environment variables
FRONTEND_URL = "https://resume-extractor.windsurf.build"

[web.ports]
8000 = "8000"

[web.healthCheck]
path = "/health"

[database]
name = "resume_extractor"
type = "mongodb"

[database.env]
# MongoDB URI will be set via environment variables
